/* =====================================================================
   §16 BUSINESSES — connected records: owners, tenants, developers,
       operators · listings · revenue by period (recorded · estimated · simulated)
   ===================================================================== */
UI.bq = ''; UI.bf = { category: '', status: '', district: '', all: false }; UI.bsort = { key: 'name', dir: 1 }; UI.bperiod = '';
function bizRows() {
  let zs = S.businesses.filter(z => UI.bf.all || bizInScope(z)); const q = norm(UI.bq); const f = UI.bf;
  if (f.category) zs = zs.filter(z => (z.category || '') === f.category); if (f.status) zs = zs.filter(z => z.status === f.status); if (f.district) zs = zs.filter(z => bizDistrictIds(z).has(f.district));
  if (q) zs = zs.filter(z => Math.max(fuzzyScore(q, z.name), fuzzyScore(q, z.reg), fuzzyScore(q, z.ticker), fuzzyScore(q, z.category), ...(z.aliases || []).map(a => fuzzyScore(q, a)), ...bizBuildings(z).map(b => fuzzyScore(q, titleOf(b)) * .8)) >= 0.3);
  const { key, dir } = UI.bsort;
  const val = z => key === 'revenue' ? (num(latestRevenue(z)?.amount) ?? -1) : key === 'locations' ? tenanciesOf(z).filter(t => t.current).length : key === 'opened' ? (num(z.yearOpened) ?? 9999) : key === 'category' ? (z.category || 'zzz').toLowerCase() : bizLabel(z).toLowerCase();
  return zs.sort((a, b) => { const va = val(a), vb = val(b); return (va < vb ? -1 : va > vb ? 1 : 0) * dir || bizLabel(a).localeCompare(bizLabel(b)); });
}
function renderBusinesses() {
  const rows = bizRows(); const all = S.businesses.filter(z => UI.bf.all || bizInScope(z)); const dists = scopeDistricts();
  const operating = all.filter(z => z.status === 'open'); const withRev = all.filter(z => (z.revenue || []).length); const listed = all.filter(z => z.exchangeListed); const cats = new Set(all.map(z => z.category).filter(Boolean));
  const periods = bizPeriods(all); const period = periods.find(p => `${p.year}|${p.half}` === UI.bperiod) || periods[0]; const totals = period ? revenueTotals(all, period.year, period.half) : null;
  const tile = (lbl, val, sub = '', cls = '') => `<div class="panel tile ${cls}"><div class="lbl">${lbl}</div><div class="val">${val}</div><div class="sub">${sub}</div></div>`;
  const ownerNames = ownerNameCandidates().length;
  return `
  <section class="dhead" style="margin-bottom:14px">
    <div><div class="code biz"><i></i>BUSINESSES · ${esc(scopeName().toUpperCase())} · ${all.length} ON FILE · ${operating.length} OPERATING</div><h2>Businesses</h2><p>Who owns, rents, develops and operates the buildings — kept as separate roles with their own dates. Listings, tickers and revenue stay distinct, and revenue is only ever what was recorded, estimated or simulated — never inferred from assessments or share prices.</p></div>
    <div class="stats"><button class="btn sm" data-act="export-biz-csv">${icon('down')} CSV</button><button class="btn sm" data-act="markets-refresh" title="Read the New A site's markets section and propose business records into the inbox (nothing is created without your click)">${icon('news')} From the site's markets</button>${ownerNames ? `<button class="btn sm" data-act="biz-from-owners" title="Create business records from the owner names already typed on buildings — you review the list first">${icon('spark')} From owner names · ${ownerNames}</button>` : ''}<button class="btn sm primary" data-act="new-business">${icon('plus')} Add business</button></div>
  </section>
  <section class="tiles">
    ${tile('OPERATING', `<span class="count" data-to="${operating.length}">0</span>`, `${all.filter(z => z.status === 'closed').length} closed · ${all.filter(z => z.status === 'relocated').length} relocated · ${all.filter(z => z.status === 'planned').length} planned`, 'biz')}
    ${tile('LOCATIONS', `<span class="count" data-to="${S.tenancies.filter(t => t.current && all.some(z => z.id === t.businessId)).length}">0</span>`, `current tenancies · ${S.tenancies.filter(t => !t.current && all.some(z => z.id === t.businessId)).length} former kept in history`)}
    ${tile('OWNERS ON RECORD', `<span class="count" data-to="${new Set(S.tenancies.filter(t => t.role === 'owner' && t.current).map(t => t.businessId)).size}">0</span>`, `${S.tenancies.filter(t => t.role === 'owner' && t.current).length} buildings with a linked owner`)}
    ${tile('WITH REVENUE', `<span class="count" data-to="${withRev.length}">0</span>`, withRev.length ? `${all.flatMap(z => z.revenue || []).filter(r => r.basis === 'recorded').length} recorded periods` : 'revenue unknown until recorded')}
    ${tile('ON THE EXCHANGE', `<span class="count" data-to="${listed.length}">0</span>`, listed.length ? listed.slice(0, 4).map(z => esc(z.ticker || bizLabel(z))).join(' · ') : 'tickers as supplied, no prices')}
    ${tile('CATEGORIES', `<span class="count" data-to="${cats.size}">0</span>`, [...cats].slice(0, 3).map(esc).join(' · ') || 'uncategorised')}
  </section>
  ${periods.length ? `<section class="panel hud" style="margin-bottom:16px"><div class="panel-head"><h3>REVENUE · ${esc(hyLabel(period.year, period.half) || period.year)}</h3><span class="note" style="display:flex;gap:8px;align-items:center">period <select data-bperiod style="background:var(--bg-2);border:1px solid var(--line-2);color:var(--ink);border-radius:4px;height:24px">${periods.map(p => `<option value="${p.year}|${p.half}" ${p === period ? 'selected' : ''}>${esc(hyLabel(p.year, p.half) || p.year)}</option>`).join('')}</select></span></div>
    <div class="grid cols-3"><div><div class="kv" style="margin:0;border:0"><div><div class="k">TOTAL · COUNTED ONCE</div><div class="v money">${fmtMoneyCompact(totals.total)}</div></div><div><div class="k">BUSINESSES COUNTED</div><div class="v num">${totals.counted}${totals.skipped ? `<small>${totals.skipped} branch${totals.skipped === 1 ? '' : 'es'} skipped — parent reports</small>` : ''}</div></div></div></div>
    <div>${hbarsHTML(REVENUE_BASIS.map(([id, l]) => ({ label: l, n: totals.byBasis[id] || 0, c: { recorded: '#39D98A', estimated: '#FFD166', simulated: '#6F8494' }[id] })).filter(x => x.n), { fmt: fmtMoneyCompact, labelW: 130 })}</div>
    <div>${hbarsHTML(topCounts(all.filter(z => revenueFor(z, period.year, period.half)), z => z.category || 'Uncategorised', 6).map(x => ({ label: x.k, n: all.filter(z => (z.category || 'Uncategorised') === x.k).reduce((a, z) => { const r = revenueFor(z, period.year, period.half); return a + (r && !(z.parentId && all.some(p => p.id === z.parentId) && revenueFor(bizById(z.parentId), period.year, period.half)) ? num(r.amount) || 0 : 0); }, 0) })), { fmt: fmtMoneyCompact, labelW: 130, color: PALETTE.marks[3] })}</div></div>
    <div class="desc-line" style="margin-top:10px">Simulated figures (from the site's market) are shown by basis and never presented as recorded revenue.</div></section>` : ''}
  <div class="toolbar" style="margin:0 0 12px">
    <label class="field"><span>Find</span><input id="bq" value="${esc(UI.bq)}" placeholder="name, alias, ticker, building…" style="width:200px"></label>
    <label class="field ${UI.bf.category ? 'on' : ''}"><span>Category</span><select data-bf="category"><option value="">Any</option>${[...new Set([...BIZ_CATEGORIES, ...cats])].map(c => `<option ${UI.bf.category === c ? 'selected' : ''}>${esc(c)}</option>`).join('')}</select></label>
    <label class="field ${UI.bf.status ? 'on' : ''}"><span>Status</span><select data-bf="status"><option value="">Any</option>${BIZ_STATUSES.map(([id, l]) => `<option value="${id}" ${UI.bf.status === id ? 'selected' : ''}>${l}</option>`).join('')}</select></label>
    ${dists.length > 1 ? `<label class="field ${UI.bf.district ? 'on' : ''}"><span>Place</span><select data-bf="district"><option value="">Any</option>${dists.map(d => `<option value="${d.id}" ${UI.bf.district === d.id ? 'selected' : ''}>${esc(d.name)}</option>`).join('')}</select></label>` : ''}
    <label class="field"><span>Sort</span><select data-bsort><option value="name" ${UI.bsort.key === 'name' ? 'selected' : ''}>Name</option><option value="category" ${UI.bsort.key === 'category' ? 'selected' : ''}>Category</option><option value="locations" ${UI.bsort.key === 'locations' ? 'selected' : ''}>Locations</option><option value="revenue" ${UI.bsort.key === 'revenue' ? 'selected' : ''}>Latest revenue</option><option value="opened" ${UI.bsort.key === 'opened' ? 'selected' : ''}>Opened</option></select></label>
    <button class="field ${UI.bf.all ? 'on' : ''}" data-bf-toggle="all" style="cursor:pointer">${icon('globe')} All jurisdictions</button>
    <span class="spacer"></span><span class="count">${rows.length}${rows.length !== all.length ? ` of ${all.length}` : ''} businesses</span>
  </div>
  ${rows.length ? `<div class="panel hud" style="padding:0"><div class="bizrows">${rows.map(z => { const ts = tenanciesOf(z); const cur = ts.filter(t => t.current); const rv = latestRevenue(z); const st = BIZ_STATUS[z.status] || BIZ_STATUS.open; const u = imgUrl(z.id); const parent = z.parentId ? bizById(z.parentId) : null; return `<div class="bz" data-open="business:${z.id}" data-hover="business:${z.id}"><div class="lg">${u ? `<img src="${u}" alt="">` : esc((z.name || '?').slice(0, 2).toUpperCase())}</div><div><div class="nm">${esc(bizLabel(z))}<small>${esc(z.reg)}${z.category ? ' · ' + esc(z.category) : ''}${parent ? ' · part of ' + esc(bizLabel(parent)) : ''}</small>${z.ticker ? `<span class="ticker">${esc(z.ticker)}</span>` : ''}</div><div class="s"><span><b>${cur.length}</b> location${cur.length === 1 ? '' : 's'}${ts.length > cur.length ? ` · ${ts.length - cur.length} former` : ''}</span><span>${[...new Set(cur.map(t => ROLE_LABEL[t.role] || t.role))].map(esc).join(' · ') || 'no building linked'}</span>${z.yearOpened != null ? `<span>since <b>${esc(hyLabel(z.yearOpened, z.halfOpened, z.yearOpenedApprox))}</b></span>` : ''}${bizDistrictIds(z).size ? `<span>${[...bizDistrictIds(z)].map(id => esc(districtById(id)?.name || '')).join(', ')}</span>` : ''}</div></div><div class="rv">${rv ? `${fmtCur(num(rv.amount), rv.currency)}<small>${esc(hyLabel(rv.year, rv.half) || rv.year)} · ${esc(BASIS[rv.basis]?.label || 'recorded')}</small>` : '<span class="muted">revenue unknown</span>'}</div><span class="status ${st.tone}"><i>●</i>${st.label}</span></div>`; }).join('')}</div></div>`
    : `<div class="panel empty"><b>${S.businesses.length ? 'No business matches' : 'No businesses yet'}</b>${S.businesses.length ? 'Try clearing the filters, or include all jurisdictions.' : `Add the first business, or create records from the owner names already typed on your buildings${ownerNames ? ` (${ownerNames} distinct names found)` : ''}.`}<br><button class="btn primary" data-act="new-business">${icon('plus')} Add business</button> <button class="btn" data-act="markets-refresh">${icon('news')} Propose from the site's markets</button>${ownerNames ? ` <button class="btn" data-act="biz-from-owners">${icon('spark')} Create from owner names</button>` : ''}</div>`}`;
}
/* owner text on buildings → candidate business records (reviewed before anything is created; never a brand in a building name) */
function ownerNameCandidates() {
  const existing = new Set(S.businesses.flatMap(z => [z.name, ...(z.aliases || [])]).map(norm).filter(Boolean));
  const groups = new Map();
  for (const b of S.buildings) { const n = (b.owner || '').trim(); if (!n || existing.has(norm(n))) continue; (groups.get(norm(n)) || groups.set(norm(n), { name: n, buildings: [] }).get(norm(n))).buildings.push(b); }
  return [...groups.values()].sort((a, b) => b.buildings.length - a.buildings.length);
}
function openOwnerImport() {
  const cands = ownerNameCandidates(); if (!cands.length) { toast('Every owner name already has a business record', 'good'); return; }
  openModal({ title: 'Create businesses from owner names', kicker: `${cands.length} NAMES`, cls: 'wide',
    body: `<p class="muted" style="font-size:12.5px;margin:12px 0 0">Each ticked name becomes a business record linked to its buildings as <b>owner</b> (current, undated). Nothing else is inferred: no category, no revenue, no tenancy. Untick anything that is a person, a placeholder or a brand that merely names a building.</p>
      <div class="toolbar" style="margin:10px 0 6px"><input id="own-q" placeholder="Filter names…" style="height:30px;flex:1;min-width:140px;background:var(--bg-2);border:1px solid var(--line-2);color:var(--ink);border-radius:5px;padding:0 8px"><button class="btn sm" id="own-all">Tick all shown</button><button class="btn sm" id="own-none">Untick all shown</button><span class="count" id="own-n"></span></div>
      <div class="list" style="max-height:340px;overflow:auto">${cands.map((c, i) => `<label class="li" style="grid-template-columns:auto 1fr auto;cursor:pointer"><input type="checkbox" data-own="${i}" checked style="accent-color:var(--biz)"><div><div class="t">${esc(c.name)}</div><div class="s">${c.buildings.slice(0, 5).map(b => esc(b.reg)).join(', ')}${c.buildings.length > 5 ? ` +${c.buildings.length - 5}` : ''}</div></div><span class="num" style="color:var(--ink-2)">${c.buildings.length}</span></label>`).join('')}</div>`,
    foot: `<button class="btn ghost" data-act="modal-close">Cancel</button><span class="spacer"></span><button class="btn primary" id="own-go">${icon('check')} Create ticked businesses</button>`,
    onOpen: m => { const rows = () => $$('[data-own]', m).map(cb => cb.closest('.li')); const count = () => { const n = $$('[data-own]:checked', m).length; m.querySelector('#own-n').textContent = `${n} of ${cands.length} ticked`; }; count(); m.addEventListener('change', count);
      m.querySelector('#own-q').addEventListener('input', e => { const q = norm(e.target.value); rows().forEach(li => { li.style.display = !q || norm(li.textContent).includes(q) ? '' : 'none'; }); });
      const setShown = v => { rows().forEach(li => { if (li.style.display !== 'none') li.querySelector('[data-own]').checked = v; }); count(); }; m.querySelector('#own-all').onclick = () => setShown(true); m.querySelector('#own-none').onclick = () => setShown(false);
      m.querySelector('#own-go').onclick = async () => { const picks = $$('[data-own]:checked', m).map(cb => cands[+cb.dataset.own]); if (!picks.length) { toast('Nothing ticked', 'warn'); return; } await takeSnapshot(`before owner import · ${picks.length}`); let nt = 0; for (const c of picks) { const z = newBusiness(S); z.name = c.name; z.orgType = /\b(city|state|authority|department|government|council)\b/i.test(c.name) ? 'government' : 'company'; z.source = 'owner field on building records'; z.sourceType = 'document'; z.confidence = 'approximate'; S.businesses.push(z); for (const b of c.buildings) { S.tenancies.push(newTenancy(z.id, b.id, 'owner')); nt++; } } commit(); closeModal(); renderView(false); toast(`${picks.length} businesses created · ${nt} owner links — review their categories and dates`, 'good'); }; } });
}
