/* =====================================================================
   §24 CLAWSON — the city assistant. Answers come from the records; every
       change it wants to make becomes a proposal in the Inbox (apply/undo
       there), newsletters become drafts you publish yourself, and the
       optional AI provider can only trigger the same validated actions.
   ===================================================================== */
const CLAW = { open: false, log: [], busy: false, view: 'chat', pending: null };
const CLAW_EXAMPLES = ['Who is the mayor?', 'Where does the mayor live?', 'Hospitals in Man A', 'Which borough is best served?', 'How is the city doing?', 'What changed this month?', 'Draft the newsletter', 'What needs fixing?', 'Backup status', 'Mark MA-0004 as a police station'];
const CLAW_FIELDS = { civic: 'object', physical: 'string', landmark: 'boolean', floors: 'number', height: 'number', condition: 'string', owner: 'string', name: 'string', market: 'string', yearBuilt: 'number', notes: 'string', unitsRes: 'number', unitsCom: 'number' };
const CLAW_KIND_LABEL = { fact: 'FROM THE RECORDS', sugg: 'PROPOSAL · NOT APPLIED', ai: 'AI PROVIDER · UNVERIFIED', act: 'DONE · IN THE ACTIVITY LOG', note: 'NOTE' };

function clawToggle(open = !CLAW.open) { CLAW.open = open; clawRender(); const b = $('#side-end .clawson'); if (b) b.setAttribute('aria-pressed', open); if (open) setTimeout(() => $('#claw-q')?.focus(), 30); }
function clawRender() {
  const el = $('#clawson'); if (!el) return; const q0 = $('#claw-q'); const keep = q0 ? { v: q0.value, f: document.activeElement === q0 || el.contains(document.activeElement) } : null; queueMicrotask(() => { const q = $('#claw-q'); if (!q || !keep) return; if (keep.v && !q.value) q.value = keep.v; if (keep.f && CLAW.open && !modalOpen()) q.focus(); }); el.classList.toggle('on', CLAW.open); if (!CLAW.open) { el.innerHTML = ''; return; }
  const ai = S.settings.ai || {};
  el.innerHTML = `<div class="ch"><div><div class="k">CLAWSON</div><div class="s">${ai.enabled ? `records + ${ai.provider === 'openai' ? 'OpenAI-compatible' : 'Anthropic'} provider` : 'answers from the records · no AI provider on'} · proposes, never changes silently</div></div>
    <div class="acts"><button class="btn ghost icon sm" data-act="claw-view" data-view="${CLAW.view === 'chat' ? 'activity' : 'chat'}" title="${CLAW.view === 'chat' ? 'Activity, proposals, drafts and undo' : 'Back to the conversation'}" aria-pressed="${CLAW.view === 'activity'}">${icon(CLAW.view === 'chat' ? 'clock' : 'chat')}</button><button class="btn ghost icon sm" data-act="claw-clear" title="Clear the conversation">${icon('trash')}</button><button class="btn ghost icon sm" data-act="clawson-toggle" title="Close (K)">${icon('x')}</button></div></div>
    <div class="cb" id="claw-log">${CLAW.view === 'activity' ? clawActivityHTML() : clawLogHTML()}</div>
    ${CLAW.view === 'chat' ? `<div class="chips">${CLAW_EXAMPLES.map(q => `<button data-act="claw-run" data-q="${esc(q)}">${esc(q)}</button>`).join('')}</div>
    <div class="ask"><input id="claw-q" placeholder="Ask Clawson — a building, a borough, a draft…" autocomplete="off"><button class="btn primary icon" data-act="claw-send" title="Ask (Enter)">${icon('spark')}</button></div>` : ''}`;
  const lg = $('#claw-log'); if (lg) lg.scrollTop = lg.scrollHeight;
}
function clawLogHTML() {
  if (!CLAW.log.length) return `<div class="msg"><span class="k">CLAWSON</span>Hi Isaiah. I read the registry — buildings, roads, transit, civic, officials, businesses, the chronicle — and answer from it. Anything I want to change goes to the Inbox as a proposal; newsletters become drafts you publish. Try a chip, or ask in your own words.</div>`;
  return CLAW.log.map(m => m.role === 'me' ? `<div class="msg me">${esc(m.text)}</div>` : `<div class="msg"><span class="k ${m.kind}">${CLAW_KIND_LABEL[m.kind] || 'NOTE'}</span>${m.html}${m.pre ? `<pre>${esc(m.pre)}</pre>` : ''}${m.hits?.length ? `<div class="hits">${m.hits.slice(0, 16).map(h => `<button data-act="claw-locate" data-kind="${esc(h.kind)}" data-id="${esc(h.id)}">${esc(h.label)}</button>`).join('')}</div>` : ''}${m.action && CLAW.pending === m.action ? `<div class="pv">${esc(m.action.summary || 'APPLY THIS?')}<button class="btn sm primary" data-act="claw-apply">${icon('check')} ${esc(m.action.okLabel || 'Send to inbox')}</button><button class="btn sm ghost" data-act="claw-cancel">Cancel</button></div>` : ''}</div>`).join('');
}
function clawActivityHTML() {
  const log = (S.news.log || []).filter(l => (l.source?.guid || '').startsWith('clawson:')); const drafts = (S.news.drafts || []).slice().reverse(); const props = (S.news.items || []).filter(it => it.source === 'clawson').flatMap(it => it.candidates || []).filter(c => !S.news.decisions[c.id]);
  return `<div class="desc-line">PROPOSALS WAITING IN THE INBOX · ${props.length}</div>${props.length ? props.map(c => `<div class="msg"><span class="k sugg">PROPOSAL</span><b>${esc(c.label)}</b><br>${esc(c.excerpt)}<div class="hits"><button data-act="claw-inbox">Open inbox</button></div></div>`).join('') : '<div class="msg">Nothing waiting.</div>'}
  <div class="desc-line" style="margin-top:6px">NEWSLETTER DRAFTS · ${drafts.length}</div>${drafts.length ? drafts.map(d => `<div class="msg"><span class="k ${d.status === 'published' ? 'act' : 'sugg'}">${d.status === 'published' ? 'PUBLISHED BY YOU' : 'DRAFT'} · ${fmtDate(d.at)}</span><b>${esc(d.title || 'Untitled')}</b><div class="hits"><button data-act="draft-open" data-id="${d.id}">Open</button><button data-act="draft-download" data-id="${d.id}">.md</button>${d.status !== 'published' ? `<button data-act="draft-published" data-id="${d.id}">Mark published</button>` : ''}<button data-act="draft-delete" data-id="${d.id}">Delete</button></div></div>`).join('') : '<div class="msg">No drafts yet — ask “Draft the newsletter”.</div>'}
  <div class="desc-line" style="margin-top:6px">CHANGES APPLIED FROM CLAWSON PROPOSALS · ${log.length}</div>${log.length ? log.slice(0, 20).map(l => `<div class="msg"><span class="k act">${l.undone ? 'UNDONE' : 'APPLIED'} · ${fmtDate(l.at)}</span><b>${esc(l.label)}</b><br>${Object.entries(l.after || {}).map(([k, v]) => `${esc(k)}: ${esc(String((l.before || {})[k] ?? '—'))} → ${esc(typeof v === 'object' ? JSON.stringify(v) : String(v ?? '—'))}`).join(' · ')}${l.undone ? '' : `<div class="hits"><button data-act="news-undo" data-log="${l.id}">Undo</button></div>`}</div>`).join('') : '<div class="msg">Nothing applied yet. Proposals are only applied when you click Apply in the Inbox, and each one can be undone there or here.</div>'}`;
}
/* ---- helpers ---- */
const clawPlace = text => { const p = text ? placeByName(text) : null; return p ? { sc: { kind: p.kind, id: p.node.id }, name: p.node.name, p } : null; };
const clawHits = list => list.map(x => x.reg && x.districtId !== undefined ? bHit(x) : x.reg && x.office !== undefined ? { kind: 'official', id: x.id, label: officialLabel(x) } : x.stopIds ? { kind: 'line', id: x.id, label: lineLabel(x) } : x.kind === 'station' || x.aliases && x.x !== undefined && !x.districtId ? { kind: 'station', id: x.id, label: x.name || x.reg } : { kind: 'building', id: x.id, label: x.reg || x.name || x.id });
function clawFindOfficial(text) { const t = norm(text); return S.officials.filter(o => o.status !== 'former').map(o => ({ o, s: Math.max(fuzzyScore(t, o.office), fuzzyScore(t, o.name), t.includes(norm(o.office)) ? 0.9 : 0) })).filter(x => x.s >= 0.6).sort((a, b) => b.s - a.s).map(x => x.o); }
function clawPropose({ entityKind = 'building', entityId, after, why, label, kind = 'clawson' }) {
  const rec = entityKind === 'building' ? byId(entityId) : entityKind === 'business' ? bizById(entityId) : entityKind === 'line' ? lineById(entityId) : stationById(entityId); if (!rec) return null;
  const before = {}; for (const k of Object.keys(after)) before[k] = JSON.parse(JSON.stringify(rec[k] ?? null));
  const c = { id: uid('cw'), kind, entityKind, entityId, label: label || (entityKind === 'building' ? `${rec.reg} · ${titleOf(rec)}` : rec.name || rec.reg), excerpt: why, before, after, eventYear: null, eventHalf: '', dateFromText: false, itemGuid: null, link: '', title: 'Clawson', published: now(), note: 'Proposed by Clawson from your words — nothing changes until you apply it here.' };
  c.conflict = candidateConflict(c); const item = { guid: 'clawson:' + c.id, title: `Clawson · ${c.label}`, link: '', published: now(), fetchedAt: now(), source: 'clawson', excerpt: why, hash: c.id, revisions: [], candidates: [c], categories: ['clawson'] }; c.itemGuid = item.guid;
  S.news.items.unshift(item); commit({ silentRender: true }); renderStatus(); return c;
}
function clawDraftNewsletter(sinceDays = 30) { const d = changeDigest({ sinceDays }); const body = digestMarkdown(d); const draft = { id: uid('nd'), at: now(), title: body.split('\n')[0].replace(/^#\s*/, ''), body, status: 'draft', scope: UI.scope, sinceDays, by: 'clawson', changes: d.total }; S.news.drafts = [...(S.news.drafts || []), draft]; commit({ silentRender: true }); return draft; }
function openDraftModal(id) {
  const d = (S.news.drafts || []).find(x => x.id === id); if (!d) return;
  openModal({ title: d.title || 'Newsletter draft', kicker: `${d.status === 'published' ? 'PUBLISHED BY YOU' : 'DRAFT'} · ${fmtDate(d.at)} · ${d.by === 'clawson' ? 'CLAWSON' : 'DIGEST'}`, cls: 'wide',
    body: `<textarea id="draft-text" style="width:100%;min-height:380px;font:12.5px/1.5 var(--font-mono);background:var(--bg-2);color:var(--ink);border:1px solid var(--line-2);border-radius:6px;padding:10px;margin-top:10px">${esc(d.body)}</textarea><div class="desc-line" style="margin-top:8px">Publishing is yours: copy or download the text and post it on the site. New A OS never posts anywhere by itself; “Mark published” only records that you did.</div>`,
    foot: `<button class="btn danger sm" data-act="draft-delete" data-id="${d.id}">${icon('trash')} Delete</button><span class="spacer"></span><button class="btn" id="draft-copy">${icon('copy')} Copy</button><button class="btn" data-act="draft-download" data-id="${d.id}">${icon('down')} .md</button>${d.status !== 'published' ? `<button class="btn" data-act="draft-published" data-id="${d.id}">${icon('check')} Mark published</button>` : ''}<button class="btn primary" id="draft-save">${icon('check')} Save</button>`,
    onOpen: m => { m.querySelector('#draft-copy').onclick = () => navigator.clipboard?.writeText(m.querySelector('#draft-text').value).then(() => toast('Draft copied', 'good'), () => toast('Clipboard blocked', 'warn')); m.querySelector('#draft-save').onclick = () => { d.body = m.querySelector('#draft-text').value; d.title = d.body.split('\n')[0].replace(/^#\s*/, ''); d.updated = now(); commit({ silentRender: true }); closeModal(); clawRender(); toast('Draft saved', 'good'); }; } });
}
/* ---- deterministic answers (tried before the map assistant's own patterns) ---- */
async function clawAnswer(q) {
  const t = q.trim(); const tl = t.toLowerCase(); let m;
  if ((m = /^(?:who(?:'s| is)|who)\s+(?:the\s+)?(.+?)(?:\s+of\s+(.+?))?\??$/i.exec(tl)) && !/\bserves?\b/.test(tl)) {
    const offs = clawFindOfficial(m[1]); const pl = m[2] ? clawPlace(m[2]) : null; const list = pl ? offs.filter(o => o.jurisdictionId === pl.sc.id || jurisdictionInScope(o.jurisdictionId, pl.sc)) : offs;
    if (list.length) return { kind: 'fact', html: list.slice(0, 3).map(o => `<b>${esc(o.name || '— unnamed —')}</b> is ${esc(o.office || 'an official')}${o.jurisdictionId && nodeById(o.jurisdictionId) ? ` of ${esc(nodeById(o.jurisdictionId).name)}` : ''} (${officialStatus(o).label.toLowerCase()}${termLabel(o) ? ', ' + esc(termLabel(o)) : ''}). Office: ${officeOf(o) ? esc(officeOf(o).name || titleOf(officeOf(o))) : 'not recorded'}. Home: ${residenceOf(o) ? esc(residenceOf(o).name || titleOf(residenceOf(o))) : 'not recorded'}.`).join('<br>'), hits: list.flatMap(o => [officeOf(o), residenceOf(o)].filter(Boolean).map(bHit)) };
    if (/mayor|governor|president|official|council|commissioner|judge|senator/.test(m[1])) return { kind: 'fact', html: `No ${esc(m[1])} is on file${pl ? ' for ' + esc(pl.name) : ''}. Add one under Civic → Officials & homes.` };
  }
  if ((m = /^(?:where does|where do)\s+(?:the\s+)?(.+?)\s+(?:live|lives|reside|work|works)\??$/i.exec(tl))) {
    const offs = clawFindOfficial(m[1]); const work = /work/.test(tl);
    if (!offs.length) return { kind: 'fact', html: `I do not know an official called “${esc(m[1])}”.` };
    return { kind: 'fact', html: offs.slice(0, 3).map(o => { const b = work ? officeOf(o) : residenceOf(o); return b ? `<b>${esc(o.name || o.office)}</b> ${work ? 'works at' : 'lives at'} <b>${esc(b.name || titleOf(b))}</b> (${esc(b.reg)}, ${esc(districtById(b.districtId)?.name || '')}${hoodById(b.neighborhoodId) ? ', ' + esc(hoodById(b.neighborhoodId).name) : ''})${b.x != null ? ` — X ${b.x} · Z ${b.z}` : ''}.` : `<b>${esc(o.name || o.office)}</b> has no ${work ? 'office building' : 'residence'} recorded — set it on the official.`; }).join('<br>'), hits: offs.map(o => (work ? officeOf(o) : residenceOf(o))).filter(Boolean).map(bHit) };
  }
  if ((m = /^(?:show|list|find|where are|which|what)?\s*(?:are\s+)?(?:the\s+)?(hospitals?|clinics?|police(?: stations?)?|fire(?: stations?)?|schools?|parks?|courts?|courthouses?|city halls?|libraries|universit(?:y|ies)|civic(?: facilities| buildings)?)(?:\s+(?:in|around|of)\s+(.+))?\??$/i.exec(tl))) {
    const w = m[1]; const type = /hospital/.test(w) ? 'hospital' : /clinic/.test(w) ? 'clinic' : /police/.test(w) ? 'police' : /fire/.test(w) ? 'fire' : /school/.test(w) ? 'school' : /park/.test(w) ? 'park' : /court/.test(w) ? 'courthouse' : /city hall/.test(w) ? 'city-hall' : /librar/.test(w) ? 'library' : /universit/.test(w) ? 'university' : null;
    const pl = m[2] ? clawPlace(m[2]) : null; if (m[2] && !pl) return { kind: 'fact', html: `I do not know a place called “${esc(m[2])}”.` };
    const rows = civicRows(pl ? pl.sc : UI.scope).filter(b => !type || civicOf(b).type === type); const name = pl ? pl.name : scopeName();
    return { kind: 'fact', html: `<b>${rows.length}</b> ${type ? civicTypeLabel(type).toLowerCase() + (rows.length === 1 ? '' : 's') : 'civic facilities'} in ${esc(name)}${rows.length ? ': ' + rows.slice(0, 6).map(b => `${esc(b.name || titleOf(b))} (${(CIVIC_STATUS[civicOf(b).status] || CIVIC_STATUS.operating).label.toLowerCase()}${num(civicOf(b).capacity) != null ? `, ${fmtInt(civicOf(b).capacity)} ${esc(CIVIC_BY_ID[civicOf(b).type]?.unit || '')}` : ''})`).join(', ') : ''}.${type && ESSENTIAL_CIVIC.includes(type) && rows.length ? ` Coverage: ${coverageReport(pl ? pl.sc : UI.scope).types[type].pct}% of placed buildings within ${COVERAGE_RADIUS[type]} blocks of an operating one.` : ''}`, hits: rows.map(bHit), highlight: rows.map(b => b.id), fit: rows.filter(b => b.x != null) };
  }
  if (/coverage|essential services?/.test(tl) && !/propose|mark/.test(tl)) { const pl = clawPlace((/(?:in|of|for)\s+(.+?)\??$/.exec(tl) || [])[1]); const sc = pl ? pl.sc : UI.scope; const cov = coverageReport(sc); return { kind: 'fact', html: `Essential coverage in <b>${esc(pl ? pl.name : scopeName())}</b>: <b>${cov.score}%</b> overall — ${ESSENTIAL_CIVIC.map(t => `${civicTypeLabel(t).toLowerCase()} ${cov.types[t].pct}% (${cov.types[t].facilities} operating)`).join(', ')}. ${cov.fully} of ${cov.placed} placed buildings reach all three${cov.places.length ? `; best ${esc(cov.places[0].name)} ${cov.places[0].pct}%, weakest ${esc(cov.places[cov.places.length - 1].name)} ${cov.places[cov.places.length - 1].pct}%` : ''}.`, hits: ESSENTIAL_CIVIC.flatMap(t => cov.types[t].gaps.slice(0, 2).map(g => bHit(g.b))) }; }
  if (/best served|underserved|worst served|service (?:in|by|score)|transit access/.test(tl)) { const pl = clawPlace((/(?:in|of|for)\s+(.+?)\??$/.exec(tl) || [])[1]); const places = serviceByPlace(pl ? pl.sc : UI.scope); if (!places.length) return { kind: 'fact', html: 'Nothing in scope to score.' }; const best = places[0], worst = places[places.length - 1]; return { kind: 'fact', html: `${places.map(p => `<b>${esc(p.name)}</b> ${p.avg ?? '—'}${p.tier === 'best' ? ' ★' : ''}`).join(' · ')}.<br>Best served: <b>${esc(best.name)}</b> (${best.pctNear}% within ${SERVICE_REACH} blk of a station, ${best.tph} trains/h). Least: <b>${esc(worst.name)}</b>${worst.avg != null ? ` (${worst.pctNear}%, ${worst.tph} trains/h)` : ' (no placed buildings)'}. Score = walk to the nearest open station, trains per hour within reach, distinct lines.` }; }
  if ((m = /^(?:how long|travel time|time)\s+(?:does it take\s+)?(?:from\s+)?(.+?)\s+to\s+(.+?)(?:\s+on\s+(?:the\s+)?(.+?))?\??$/i.exec(tl))) {
    const find = n => S.stations.map(s => ({ s, sc: Math.max(fuzzyScore(norm(n), s.name), ...(s.aliases || []).map(a => fuzzyScore(norm(n), a))) })).filter(x => x.sc >= 0.6).sort((a, b) => b.sc - a.sc)[0]?.s;
    const a = find(m[1]), b = find(m[2]); if (!a || !b) return { kind: 'fact', html: `I need two station names — ${!a ? `“${esc(m[1])}”` : `“${esc(m[2])}”`} is not a station on file.` };
    const lines = linesAtStation(a).filter(l => linesAtStation(b).includes(l) && l.status === 'open'); const l = m[3] ? lines.find(x => fuzzyScore(norm(m[3]), x.name) >= 0.6 || fuzzyScore(norm(m[3]), x.shortName) >= 0.8) || lines[0] : lines[0];
    if (!l) return { kind: 'fact', html: `${esc(a.name)} and ${esc(b.name)} share no open line — a transfer is needed, and I do not time transfers yet.` };
    const j = lineJourneyTime(l, a.id, b.id); const svc = lineService(l); if (!j) return { kind: 'fact', html: `On ${esc(lineLabel(l))} the time cannot be computed — a stop between them has no coordinates.` };
    return { kind: 'fact', html: `<b>${esc(a.name)} → ${esc(b.name)}</b> on ${esc(lineLabel(l))}: about <b>${fmtMins(j.sec)}</b> on board (${j.stops} stop${j.stops === 1 ? '' : 's'}, ${fmtInt(j.dist)} blk, ${j.basis}) plus an average wait of ${fmtMins(svc.headwayMin * 30)} at a ${svc.headwayMin}-min headway — about ${fmtMins(j.sec + svc.headwayMin * 30)} door to door.`, hits: [{ kind: 'line', id: l.id, label: lineLabel(l) }, { kind: 'station', id: a.id, label: a.name }, { kind: 'station', id: b.id, label: b.name }] };
  }
  if (/how is (?:the city|new a|.+?) doing|city health|health score|state of the city/.test(tl)) { const pl = clawPlace((/how is (.+?) doing/.exec(tl) || [])[1]); const h = cityHealth(pl ? pl.sc : UI.scope); return { kind: 'fact', html: `<b>${esc(pl ? pl.name : scopeName())}</b> scores <b>${h.overall}/100</b>. ${h.cards.map(c => `${c.label.toLowerCase()} ${esc(String(c.value))}${c.unit ? ' ' + esc(c.unit) : ''}`).join(' · ')}. ${h.cards.filter(c => c.tone === 'bad').length ? 'Weak spots: ' + h.cards.filter(c => c.tone === 'bad').map(c => c.label.toLowerCase() + ' — ' + esc(c.sub)).join('; ') + '.' : 'Nothing in the red.'}`, action: { type: 'nav', nav: 'overview', summary: 'OPEN HOME?', okLabel: 'Open Home' } }; }
  if ((m = /what(?:'s| has| is)?\s*(?:changed|new)(?:\s+(?:this|in the last|in the past|since)\s+(.+?))?\??$/i.exec(tl)) || (m = /^(?:changes?|digest)(?:\s+(?:this|for the|last)\s+(.+?))?\??$/i.exec(tl))) {
    const days = /week/.test(m[1] || '') ? 7 : /year/.test(m[1] || '') ? 365 : /(\d+)\s*days?/.test(m[1] || '') ? +/(\d+)/.exec(m[1])[1] : 30; const d = changeDigest({ sinceDays: days });
    return { kind: 'fact', html: `In the last ${days} days in <b>${esc(scopeName())}</b>: ${d.completed.length} completed, ${d.started.length} started, ${d.demolished.length} demolished, ${d.lines.length} line${d.lines.length === 1 ? '' : 's'} and ${d.stations.length} station${d.stations.length === 1 ? '' : 's'}, ${d.businesses.length} business${d.businesses.length === 1 ? '' : 'es'}, ${d.officials.length} official${d.officials.length === 1 ? '' : 's'}, ${d.added.length} record${d.added.length === 1 ? '' : 's'} added, ${d.archive.length} chronicle entr${d.archive.length === 1 ? 'y' : 'ies'} — ${d.total} change${d.total === 1 ? '' : 's'} in all.`, hits: [...d.completed, ...d.started, ...d.demolished, ...d.added].slice(0, 10).map(bHit), action: { type: 'draft-newsletter', sinceDays: days, summary: 'DRAFT A NEWSLETTER FROM THIS?', okLabel: 'Draft it' } };
  }
  if (/draft|write|prepare|compose/.test(tl) && /newsletter|digest|bulletin|update post|article/.test(tl)) { const days = /week/.test(tl) ? 7 : /year/.test(tl) ? 365 : /(\d+)\s*days?/.test(tl) ? +/(\d+)/.exec(tl)[1] : 30; return clawExecute({ type: 'draft-newsletter', sinceDays: days }); }
  if (/publish|post (?:it|this|the newsletter)|send (?:it|the newsletter)/.test(tl)) return { kind: 'note', html: 'I cannot post to the site — New A OS has no publishing endpoint and never writes to the website. Open a draft under Activity, copy or download it, and publish it yourself; then “Mark published” so the record shows it.' };
  if ((m = /^(?:why is|what is|what's|how much is)\s+(.+?)\s+(?:worth|valued at|estimated at)(?:\s+that|\s+so much|\s+this|\s+that much)?\??$/i.exec(tl)) || (m = /^(?:value|valuation|estimate)\s+(?:of|for)\s+(.+?)\??$/i.exec(tl))) {
    const b = buildingByText(m[1]); if (!b) return { kind: 'fact', html: `I cannot find a building matching “${esc(m[1])}”.` }; if (isHist(b)) return { kind: 'fact', html: `${esc(b.reg)} is demolished — no estimate.`, hits: [bHit(b)] };
    const v = valuationOf(b); const e = v.override ? v.est : v;
    return { kind: 'fact', html: `<b>${esc(b.reg)} ${esc(b.name || titleOf(b))}</b> is estimated at <b>${fmtMoney(v.value)}</b>${v.override ? ` (your override${v.reason ? ': ' + esc(v.reason) : ''}; the model says ${fmtMoney(e.value)})` : ''}. Base ${fmtMoney(Math.round(e.base))} — ${esc(e.baseBasis)}. Adjustments: ${e.factors.length ? e.factors.map(f => `${esc(f.label)} ${f.pct > 0 ? '+' : ''}${f.pct}% (${esc(f.why)})`).join('; ') : 'none'} → ${e.totalPct > 0 ? '+' : ''}${e.totalPct}%. Confidence: ${e.confidence}. Factors are set under Vault &amp; settings.`, hits: [bHit(b)] };
  }
  if (/what needs fixing|needs? (?:fixing|attention|work)|data quality|quality check|issues|problems|checks/.test(tl)) { const issues = allIssues(); const sug = qualitySuggestions(); return { kind: 'fact', html: `<b>${issues.length}</b> flagged in ${esc(scopeName())}: ${issues.filter(i => i.level === 'bad').length} problems, ${issues.filter(i => i.level === 'warn').length} warnings, ${issues.filter(i => i.level === 'info').length} notes.${issues[0] ? ` First: ${esc(issues[0].title || issues[0].reg)} — ${esc(truncate(issues[0].text, 110))}` : ''}${sug.length ? `<br>The assistant can help with: ${sug.map(s => `${esc(s.label.toLowerCase())} (${s.items.length}${s.fix ? ', fixable' : ''})`).join(', ')} — see Home → Data quality.` : ''}`, hits: issues.slice(0, 8).filter(i => i.kind === 'building').map(i => ({ kind: 'building', id: i.id, label: `${i.reg} ${truncate(i.title || '', 20)}` })), action: { type: 'nav', nav: 'issues', summary: 'OPEN THE ISSUE LIST?', okLabel: 'Open issues' } }; }
  if (/backup|snapshot|restore point/.test(tl)) { let snaps = []; try { snaps = await listSnapshots(); } catch { } const w = S.world?.backups || {}; const last = (w.history || [])[0]; return { kind: 'fact', html: `<b>${snaps.length}</b> snapshot${snaps.length === 1 ? '' : 's'} in this browser${snaps[0] ? ` (latest ${fmtDate(new Date(snaps[0].ts).toISOString())}, “${esc(snaps[0].label || '')}”)` : ''}. Vault: ${VAULT.status === 'granted' ? `linked to “${esc(VAULT.name)}”${VAULT.lastWrite ? ', last write ' + fmtTime(VAULT.lastWrite) : ''}` : 'not linked — link a folder under Vault so Registry.json is written to disk'}. Verified backups: ${last ? `last ${fmtDate(last.at)} (${esc(last.kind || 'incremental')}${last.verified ? ', verified' : ', unverified'})` : 'none yet — the New A OS bridge runs them when it is connected'}. Last restore test: ${w.lastRestoreTest ? fmtDate(w.lastRestoreTest) : 'never'}.`, action: { type: 'nav', nav: 'vault', summary: 'OPEN VAULT & BACKUPS?', okLabel: 'Open Vault' } }; }
  if ((m = /^(?:projects?)(?:\s+(?:in|for)\s+(.+))?\??$/i.exec(tl)) || /^(?:what|which) projects/.test(tl)) { const pl = clawPlace(m && m[1]); const ps = projectsIn(pl ? pl.sc : UI.scope); return { kind: 'fact', html: ps.length ? `<b>${ps.length}</b> project${ps.length === 1 ? '' : 's'}: ${ps.map(p => `${esc(p.name || p.reg)} (${projectStage(p).label.toLowerCase()}${p.targetYear ? ', target ' + esc(hyLabel(p.targetYear, p.targetHalf)) : ''})`).join('; ')}.` : 'No projects tracked yet — add one from Home → Project tracker.', hits: ps.flatMap(p => (p.buildingIds || []).slice(0, 2).map(id => byId(id)).filter(Boolean).map(bHit)) }; }
  if ((m = /^(?:tell me about|describe|profile(?: of)?|about)\s+(.+?)\??$/i.exec(tl))) { const pl = clawPlace(m[1]); if (pl) { const pr = placeProfile(pl.sc); return { kind: 'fact', html: pr.paragraphs.map(esc).join('<br>'), action: { type: 'scope', sc: pl.sc, summary: `LOOK AT ${pl.name.toUpperCase()}?`, okLabel: 'Look at it' } }; } const b = buildingByText(m[1]); if (b) { const d = districtById(b.districtId); const v = isHist(b) ? null : valuationOf(b); const c = civicOf(b); const offs = officialsOf(b); return { kind: 'fact', html: `<b>${esc(b.reg)} ${esc(b.name || titleOf(b))}</b> — ${esc(physicalOf(b.physical).label.toLowerCase())}${b.landmark ? ', landmark' : ''} in ${esc(d?.name || '')}${hoodById(b.neighborhoodId) ? ', ' + esc(hoodById(b.neighborhoodId).name) : ''}. ${b.yearBuilt != null ? `Completed ${esc(builtHTML(b))}. ` : ''}${b.floors ? `${b.floors} floors. ` : ''}${b.bldgClass ? `Class ${esc(b.bldgClass)}. ` : ''}${c ? `Civic: ${esc(civicTypeLabel(c.type))}, ${(CIVIC_STATUS[c.status] || CIVIC_STATUS.operating).label.toLowerCase()}. ` : ''}${offs.length ? offs.map(o => `${o.residenceBuildingId === b.id ? 'Home' : 'Office'} of ${esc(o.office || 'an official')}${o.name ? ' ' + esc(o.name) : ''}. `).join('') : ''}${v ? `Estimated ${fmtMoney(v.value)}${num(b.assessTotal) ? ` (assessed ${fmtMoney(num(b.assessTotal))})` : ''}. ` : ''}${currentTenanciesAt(b).length ? `Tenants: ${currentTenanciesAt(b).map(t => esc(bizLabel(bizById(t.businessId) || {}))).join(', ')}.` : ''}`, hits: [bHit(b)] }; } }
  if ((m = /^(?:mark|make|set|record|flag)\s+(.+?)\s+as\s+(?:a\s+|an\s+|the\s+)?(.+?)\??$/i.exec(tl))) {
    const b = buildingByText(m[1]); if (!b) return { kind: 'fact', html: `I cannot find a building matching “${esc(m[1])}”.` }; const w = m[2];
    const civicType = CIVIC_TYPES.find(t => norm(t.label) === norm(w) || norm(t.label).startsWith(norm(w)) || norm(w).includes(t.id.replace('-', ' ')) || (t.id === 'police' && /police/.test(w)) || (t.id === 'fire' && /fire/.test(w)) || (t.id === 'city-hall' && /city hall/.test(w)) || (t.id === 'white-house' && /white house/.test(w)));
    let after = null, why = `You said: “${t}”.`;
    if (civicType) after = { civic: { type: civicType.id, status: 'operating', capacity: b.civic?.capacity ?? null, jurisdictionId: b.civic?.jurisdictionId || null, notes: b.civic?.notes || '' } };
    else if (/landmark/.test(w)) after = { landmark: true };
    else if (/demolished|gone|torn down/.test(w)) after = { physical: 'demolished' };
    else if (/under construction|construction/.test(w)) after = { physical: 'construction' };
    else if (/vacant/.test(w)) after = { physical: 'vacant-lot' };
    else if (/closed/.test(w)) after = { physical: 'closed' };
    else if (/standing|open/.test(w)) after = { physical: 'standing' };
    else if (/for sale/.test(w)) after = { market: 'for-sale' }; else if (/for lease|for rent/.test(w)) after = { market: 'for-lease' }; else if (/sold/.test(w)) after = { market: 'sold' };
    else if (/excellent|good|fair|poor/.test(w)) after = { condition: /excellent/.test(w) ? 'excellent' : /good/.test(w) ? 'good' : /fair/.test(w) ? 'fair' : 'poor' };
    else if (/public/.test(w)) after = { public: !/not|private/.test(w) }; else if (/private/.test(w)) after = { public: false };
    if (!after) return { kind: 'note', html: `I can propose civic types, landmark, physical and market status, condition and public/private — not “${esc(w)}”.` };
    const action = { type: 'propose', entityId: b.id, after, why, summary: `SEND TO THE INBOX: ${b.reg} → ${Object.entries(after).map(([k, v]) => `${k} = ${typeof v === 'object' ? (v.type || JSON.stringify(v)) : v}`).join(', ')}`, okLabel: 'Propose' };
    return { kind: 'sugg', html: `I would set <b>${Object.entries(after).map(([k, v]) => `${esc(k)} → ${esc(typeof v === 'object' ? civicTypeLabel(v.type) : String(v))}`).join(', ')}</b> on <b>${esc(b.reg)} ${esc(b.name || titleOf(b))}</b>. That goes to the Inbox as a proposal; nothing changes until you apply it there, and it can be undone.`, hits: [bHit(b)], action };
  }
  if ((m = /^(?:set|change|update)\s+(.+?)(?:'s)?\s+(floors?|height|owner|name|notes?|year built|residential units|commercial units)\s+(?:to|=|as)\s+(.+?)\??$/i.exec(tl))) {
    const b = buildingByText(m[1]); if (!b) return { kind: 'fact', html: `I cannot find a building matching “${esc(m[1])}”.` }; const f = m[2]; const raw = m[3].trim();
    const field = /floor/.test(f) ? 'floors' : /height/.test(f) ? 'height' : /owner/.test(f) ? 'owner' : /name/.test(f) ? 'name' : /note/.test(f) ? 'notes' : /year/.test(f) ? 'yearBuilt' : /residential/.test(f) ? 'unitsRes' : 'unitsCom';
    const value = CLAW_FIELDS[field] === 'number' ? num(raw) : raw; if (CLAW_FIELDS[field] === 'number' && value == null) return { kind: 'note', html: `“${esc(raw)}” is not a number.` };
    const action = { type: 'propose', entityId: b.id, after: { [field]: value }, why: `You said: “${t}”.`, summary: `SEND TO THE INBOX: ${b.reg} ${field} → ${value}`, okLabel: 'Propose' };
    return { kind: 'sugg', html: `Propose <b>${esc(field)} = ${esc(String(value))}</b> on <b>${esc(b.reg)} ${esc(b.name || titleOf(b))}</b> (currently ${esc(String(b[field] ?? '—'))})? It goes to the Inbox for your Apply.`, hits: [bHit(b)], action };
  }
  const a = asstAnswer(q); if (a.unknown || /did not understand/.test(a.html)) a.unknown = true; return a;
}
/* ---- run · execute · apply ---- */
async function clawRun(q) {
  q = (q || '').trim(); if (!q || CLAW.busy) return; CLAW.view = 'chat'; CLAW.log.push({ role: 'me', text: q }); CLAW.pending = null; CLAW.busy = true; clawRender();
  let a; try { a = await clawAnswer(q); } catch (e) { console.error(e); a = { kind: 'note', html: `Something went wrong reading the records: ${esc(e.message)}` }; }
  if (a.unknown && S.settings.ai?.enabled) { CLAW.log.push({ role: 'bot', kind: 'note', html: 'Asking the AI provider…' }); clawRender(); const ai = await clawAI(q); CLAW.log.pop(); if (ai) a = ai; }
  const msg = { role: 'bot', kind: a.kind, html: a.html, hits: a.hits || [], action: a.action || null, pre: a.pre || null }; CLAW.log.push(msg); if (CLAW.log.length > 60) CLAW.log.splice(0, CLAW.log.length - 60);
  if (a.highlight?.length && UI.nav === 'map') { MAPW.highlight = { ids: new Set(a.highlight), until: Date.now() + 60000 }; mapDraw(); }
  if (a.action) { if (a.autoApply) clawExecute(a.action); else CLAW.pending = a.action; }
  CLAW.busy = false; clawRender();
}
function clawExecute(action) {
  switch (action.type) {
    case 'nav': if (action.nav === 'issues') openIssuesModal(); else if (action.nav === 'vault') openDataModal(); else setNav(action.nav); return { kind: 'act', html: 'Opened.' };
    case 'scope': setScope(action.sc); return { kind: 'act', html: `Now looking at ${esc(scopeName())}.` };
    case 'select': mapLocate({ kind: action.kind, id: action.id }); return { kind: 'act', html: 'Shown on the map.' };
    case 'open-playback': if (action.scope) setScope(action.scope); openHistoryViewer({ year: action.year, half: action.half || 'E' }); return { kind: 'act', html: `Playback opened at ${esc(hyLabel(action.year, action.half || 'E'))}.` };
    case 'draft-newsletter': { const d = clawDraftNewsletter(action.sinceDays || 30); return { kind: 'act', html: `Draft “<b>${esc(d.title)}</b>” written from ${d.changes} change${d.changes === 1 ? '' : 's'} in the last ${d.sinceDays} days and saved (Activity → Drafts). It is yours to edit and publish — I never post anything.`, pre: d.body.split('\n').slice(0, 14).join('\n') + (d.body.split('\n').length > 14 ? '\n…' : ''), action: { type: 'open-draft', id: d.id, summary: 'OPEN THE DRAFT?', okLabel: 'Open' } }; }
    case 'open-draft': openDraftModal(action.id); return { kind: 'act', html: 'Draft opened.' };
    case 'propose': { const c = clawPropose({ entityId: action.entityId, after: action.after, why: action.why, label: action.label }); if (!c) return { kind: 'note', html: 'That record is gone.' }; return { kind: 'act', html: `Proposal for <b>${esc(c.label)}</b> is in the Inbox${c.conflict && c.conflict !== 'already' ? ` — flagged: ${esc(c.conflict)}` : c.conflict === 'already' ? ' — the record already says this' : ''}. Apply it there; every applied proposal can be undone.`, hits: [{ kind: 'inbox', id: '', label: 'Open inbox' }] }; }
    case 'set-road': case 'add-stop': case 'mode': asstExecute(action); return { kind: 'act', html: 'Done — see the toast to undo.' };
  }
  return { kind: 'note', html: 'That action is not available.' };
}
function clawApply() { const a = CLAW.pending; if (!a) return; CLAW.pending = null; const r = clawExecute(a); if (r) { CLAW.log.push({ role: 'bot', kind: r.kind, html: r.html, hits: r.hits || [], pre: r.pre || null, action: r.action || null }); if (r.action) CLAW.pending = r.action; } clawRender(); }
function clawCancel() { CLAW.pending = null; clawRender(); }
function clawLocate(kind, id) { if (kind === 'inbox') { openNewsInbox(); return; } if (kind === 'official') { openOfficialModal(id); return; } if (UI.nav === 'map') mapLocate({ kind, id }); else openRecord(kind, id); }
/* ---- optional AI provider: Anthropic Messages or an OpenAI-compatible endpoint; the key never leaves this browser ---- */
async function clawAI(q) {
  let key = null; try { key = await idbGet('handles', 'aiKey'); } catch { }
  const ai = S.settings.ai || {}; if (!key) return { kind: 'note', html: 'The AI provider is switched on but no key is stored — add one under Vault & settings. Everything from the records still works.' };
  const hits = flatItems(searchAll(q, { limit: 6 })).slice(0, 14).map(h => ({ kind: h.kind, id: h.id, title: h.title, sub: h.sub }));
  const h = cityHealth(); const sc = UI.scope;
  const context = { today: new Date().toISOString().slice(0, 10), scope: scopeName(sc), health: `${h.overall}/100`, counts: { buildings: scopeBuildings(sc).length, roads: S.roads.length, lines: S.lines.length, stations: S.stations.length, businesses: S.businesses.length, civic: civicRows(sc).length, officials: officialsIn(sc).length, projects: S.projects.length }, officials: officialsIn(sc).slice(0, 12).map(o => ({ office: o.office, name: o.name, status: o.status, office_building: officeOf(o)?.reg || null, home: residenceOf(o)?.reg || null })), matches: hits.map(x => { const b = x.kind === 'building' || x.kind === 'historical' ? byId(x.id) : null; return b ? { id: b.id, reg: b.reg, title: titleOf(b), name: b.name, district: districtById(b.districtId)?.name, physical: b.physical, yearBuilt: b.yearBuilt, floors: b.floors, civic: b.civic?.type || null, landmark: b.landmark } : x; }) };
  const system = `You are Clawson, the assistant inside New A OS, a private registry of a Minecraft city. Answer ONLY from the context; never invent records, dates, names or numbers. Reply with strict JSON: {"answer": string, "highlights": [ids from matches], "actions": [...]}. Allowed actions: {"type":"select","id":<match id>} · {"type":"open-playback","year":2018,"half":"E"|"L"} · {"type":"propose","id":<match id>,"after":{<field>:<value>},"why":string} with fields ${Object.keys(CLAW_FIELDS).join(', ')} (a proposal is reviewed by the user, never applied by you) · {"type":"draft-newsletter","sinceDays":30}. Keep answers under 120 words.`;
  const user = `Question: ${q}\n\nContext: ${JSON.stringify(context)}`;
  try {
    let text = '';
    if ((ai.provider || 'anthropic') === 'anthropic') {
      const res = await bridgeFetch(ai.endpoint || 'https://api.anthropic.com/v1/messages', { method: 'POST', headers: { 'content-type': 'application/json', 'x-api-key': key, 'anthropic-version': '2023-06-01', 'anthropic-dangerous-direct-browser-access': 'true' }, body: JSON.stringify({ model: ai.model || 'claude-sonnet-5-5', max_tokens: 700, system, messages: [{ role: 'user', content: user }] }) });
      if (!res.ok) return { kind: 'note', html: `The provider answered HTTP ${res.status}${res.status === 401 ? ' — check the key' : res.status === 404 ? ' — check the model name' : ''}. Answers from the records still work.` };
      const data = await res.json(); text = (data.content || []).map(c => c.text || '').join('');
    } else {
      const res = await bridgeFetch(ai.endpoint || 'https://api.openai.com/v1/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` }, body: JSON.stringify({ model: ai.model || 'gpt-4o-mini', temperature: 0, response_format: { type: 'json_object' }, messages: [{ role: 'system', content: system }, { role: 'user', content: user }] }) });
      if (!res.ok) return { kind: 'note', html: `The provider answered HTTP ${res.status}. Answers from the records still work.` };
      const data = await res.json(); text = data.choices?.[0]?.message?.content || '';
    }
    let out; try { out = JSON.parse(text.replace(/^```(?:json)?|```$/g, '').trim()); } catch { return { kind: 'ai', html: esc(text || 'Empty answer.') }; }
    const ids = new Set(hits.map(x => x.id)); const hl = (out.highlights || []).filter(id => ids.has(id)); const hitObjs = hits.filter(x => hl.includes(x.id)).map(x => ({ kind: x.kind === 'historical' ? 'building' : x.kind, id: x.id, label: x.title }));
    let action = null, ignored = 0; for (const a of Array.isArray(out.actions) ? out.actions : (out.action ? [out.action] : [])) {
      if (!a || typeof a !== 'object') continue;
      if (a.type === 'select' && ids.has(a.id)) action = { type: 'select', kind: hits.find(x => x.id === a.id).kind === 'historical' ? 'building' : hits.find(x => x.id === a.id).kind, id: a.id, summary: 'SHOW IT ON THE MAP?', okLabel: 'Show' };
      else if (a.type === 'open-playback' && num(a.year) != null) action = { type: 'open-playback', year: num(a.year), half: a.half === 'L' ? 'L' : 'E', summary: `OPEN PLAYBACK AT ${a.year}?`, okLabel: 'Open' };
      else if (a.type === 'propose' && ids.has(a.id) && byId(a.id) && a.after && typeof a.after === 'object' && Object.keys(a.after).every(k => CLAW_FIELDS[k] && (CLAW_FIELDS[k] === 'object' ? typeof a.after[k] === 'object' : typeof a.after[k] === CLAW_FIELDS[k]))) action = { type: 'propose', entityId: a.id, after: a.after, why: `AI provider: ${String(a.why || '').slice(0, 200)} (from “${q}”)`, summary: `SEND TO THE INBOX: ${byId(a.id).reg} → ${Object.keys(a.after).join(', ')}`, okLabel: 'Propose' };
      else if (a.type === 'draft-newsletter') action = { type: 'draft-newsletter', sinceDays: clamp(num(a.sinceDays) || 30, 1, 365), summary: 'DRAFT A NEWSLETTER?', okLabel: 'Draft it' };
      else ignored++;
      if (action) break;
    }
    return { kind: 'ai', html: esc(String(out.answer || '')) + (ignored ? ' <span class="muted">(The provider proposed an action that is not allowed or names unknown records — ignored.)</span>' : ''), hits: hitObjs, highlight: hl, action };
  } catch (e) { return { kind: 'note', html: `Could not reach the provider: ${esc(e.message)}. Answers from the records still work.` }; }
}

/* ---- drafts inside the Inbox ---- */
function draftsInboxHTML() {
  const ds = (S.news.drafts || []).slice().reverse();
  return `<div class="list" style="margin-top:12px">${ds.length ? ds.map(d => `<div class="li"><div><div class="t">${esc(d.title || 'Untitled')} ${d.status === 'published' ? '<span class="mk good">PUBLISHED BY YOU</span>' : '<span class="mk warn">DRAFT</span>'}${d.by === 'clawson' ? ' <span class="mk">CLAWSON</span>' : ''}</div><div class="s">${fmtDate(d.at)} · last ${d.sinceDays} days · ${d.body.split('\n').length} lines</div></div><div class="acts"><button class="btn sm" data-act="draft-open" data-id="${d.id}">${icon('edit')} Open</button><button class="btn sm ghost" data-act="draft-download" data-id="${d.id}">${icon('down')} .md</button>${d.status !== 'published' ? `<button class="btn sm ghost" data-act="draft-published" data-id="${d.id}">${icon('check')} Published</button>` : ''}<button class="btn sm ghost" data-act="draft-delete" data-id="${d.id}">${icon('trash')}</button></div></div>`).join('') : `<div class="li empty">No newsletter drafts yet — ask Clawson to “Draft the newsletter”, or use Change digest on Home.</div>`}</div><div class="desc-line" style="margin-top:8px">Drafts stay in this registry. Publishing is done by you on the site; New A OS never posts.</div>`;
}
