'use strict';
const fs = require('fs'); const path = require('path'); const os = require('os'); const http = require('http');
const nbt = require('../lib/nbt'); const anvil = require('../lib/anvil'); const world = require('../lib/world'); const backup = require('../lib/backup'); const synth = require('./synth'); const { createServer } = require('../server');
let checks = 0, failures = 0; const ok = (c, m) => { checks++; if (!c) { failures++; console.log('  ✗ FAIL:', m); } else console.log('  ✓', m); };
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'newa-os-test-'));
const snapshot = dir => { const out = {}; for (const rel of backup.listFiles(dir)) { const st = fs.statSync(path.join(dir, rel)); out[rel] = `${st.size}:${st.mtimeMs}:${backup.sha(path.join(dir, rel))}`; } return out; };
(async () => {
  console.log('\nA · NBT round trip');
  const longs = { hi: new Uint32Array([0x12345678, 0]), lo: new Uint32Array([0x9abcdef0, 1]), length: 2 };
  const buf = nbt.write('root', { i: 7, s: 'héllo', d: 1.5, b: nbt.tag(nbt.T.BYTE, -3), list: [{ Name: 'minecraft:stone' }, { Name: 'minecraft:air' }], bytes: Buffer.from([1, 2, 3]), ints: new Int32Array([4, 5]), longs, nested: { deep: { x: 1 } } });
  const r = nbt.parse(buf).value;
  ok(r.i === 7 && r.s === 'héllo' && r.d === 1.5 && r.b === -3 && r.list.length === 2 && r.list[1].Name === 'minecraft:air' && r.bytes.length === 3 && r.ints[1] === 5 && r.longs.hi[0] === 0x12345678 && r.longs.lo[0] === 0x9abcdef0 && r.longs.lo[1] === 1 && r.nested.deep.x === 1, 'all tag types survive write → parse (byte, int, double, string, list, byte/int/long arrays, nested compounds)');
  console.log('\nB · packed block states');
  const idx = new Uint16Array(4096); for (let i = 0; i < 4096; i++) idx[i] = i % 23;
  ok(anvil.unpack(synth.pack(idx, 23), 23, false).every((v, i) => v === idx[i]), 'non-spanning packing (1.16+) unpacks exactly (23-entry palette → 5 bits)');
  ok(anvil.unpack(synth.packSpanning(idx, 23), 23, true).every((v, i) => v === idx[i]), 'spanning packing (1.13–1.15) unpacks exactly');
  const idx2 = new Uint16Array(4096); for (let i = 0; i < 4096; i++) idx2[i] = i % 300; ok(anvil.unpack(synth.pack(idx2, 300), 300, false).every((v, i) => v === idx2[i]), '9-bit entries straddling the 32-bit halves unpack exactly');
  console.log('\nC · synthetic world scans (1.18+, 1.16, 1.13 spanning, legacy 1.12)');
  const registry = { buildings: [{ id: 'b1', reg: 'TT-0001', name: 'Tower', x: 34, z: 113, height: null, floors: null, physical: 'standing' }, { id: 'b2', reg: 'TT-0002', name: 'Ghost', x: 150, z: 150, height: 20, physical: 'standing' }, { id: 'b3', reg: 'TT-0003', name: 'Gone', x: 20, z: 20, physical: 'demolished' }], roads: [{ id: 'r1', reg: 'RD-0001', name: 'Main Street', geometry: [[10, 102], [80, 102]] }] };
  for (const fmt of ['1.18', '1.16', '1.13', '1.12']) {
    const dir = synth.makeWorld(path.join(tmp, 'world-' + fmt), fmt); const before = snapshot(dir);
    const res = world.scan(dir, { bounds: { x1: 0, z1: 0, x2: 175, z2: 175 }, registry, renderFile: path.join(tmp, `render-${fmt}.png`), stamp: '2026-10-05T00:00:00Z' });
    const tower = res.clusters.find(c => c.bbox.x1 === 30); const house = res.clusters.find(c => c.bbox.x1 === 60); const road = res.roads[0];
    ok(res.summary.chunks === 121 && res.summary.errors.length === 0, `${fmt}: 121 chunks read, no errors (${JSON.stringify(res.summary.formats)})`);
    ok(res.clusters.length === 2 && tower && tower.bbox.x2 === 39 && tower.bbox.z1 === 110 && tower.bbox.z2 === 117 && tower.size === 80 && tower.height === 12 && tower.x === 35 && tower.z === 114 && tower.material === 'gray_concrete' && tower.footprint && tower.floorsEstimate === 3, `${fmt}: tower found — 10×8 footprint, 12 high, middle X 35 · Z 114, gray concrete, rectangular footprint; the tree is not a building`);
    ok(house && house.height === 4 && house.size === 36 && house.material === 'bricks', `${fmt}: brick house found — 6×6, 4 high`);
    ok(res.roads.length === 1 && road.orientation === 'east-west' && road.width === 5 && road.length === 70 && Math.abs(road.geometry[0][1] - 102) <= 0.5 && road.geometry[0][0] === 10 && road.geometry[1][0] === 80, `${fmt}: one east-west road, 70 long, 5 wide, centre line z≈102`);
    const kinds = res.summary.byKind;
    ok(kinds['world-update'] === 1 && kinds['world-new'] === 1 && kinds['world-missing'] === 1 && kinds['world-road-confirm'] === 1 && !kinds['world-road'], `${fmt}: proposals — tower matched to TT-0001 (height + footprint update), house is new, TT-0002 missing, Main Street confirmed, demolished TT-0003 ignored`);
    const upd = res.proposals.find(p => p.kind === 'world-update'); const nw = res.proposals.find(p => p.kind === 'world-new');
    ok(upd.after.height === 12 && upd.after.footprint && !('x' in upd.after) && nw.create.x === 63 && nw.create.z === 115 && /Detected in the world scan of 2026-10-05/.test(nw.create.notes) && nw.create.sourceType === 'world', `${fmt}: update proposes height 12 + footprint (coordinates fine, 1 blk off); new building gets middle coordinates X 63 · Z 115 and a dated note`);
    ok(JSON.stringify(snapshot(dir)) === JSON.stringify(before) && !fs.existsSync(path.join(dir, 'region', 'r.0.0.mca.tmp')), `${fmt}: the world folder is byte-for-byte untouched after the scan`);
    const pngBuf = fs.readFileSync(path.join(tmp, `render-${fmt}.png`)); ok(pngBuf.slice(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])) && pngBuf.readUInt32BE(16) === 176 && pngBuf.readUInt32BE(20) === 176 && res.render.x === 0 && res.render.scale === 1, `${fmt}: render is a 176×176 PNG placed at X 0 · Z 0, 1 block per pixel`);
  }
  console.log('\nD · verified incremental backups');
  const vault = path.join(tmp, 'vault'); fs.mkdirSync(path.join(vault, 'images'), { recursive: true }); fs.writeFileSync(path.join(vault, 'Registry.json'), JSON.stringify({ buildings: [{ id: 1 }] })); fs.writeFileSync(path.join(vault, 'images', 'a.png'), Buffer.from('png-a')); const bdir = path.join(tmp, 'backups');
  const m1 = backup.run({ vaultDir: vault, backupDir: bdir, now: new Date('2026-10-05T10:00:00Z') });
  ok(m1.kind === 'full' && m1.status === 'ok' && m1.verified && m1.changedCount === 2 && Object.keys(m1.files).length === 2, `first run is a verified full backup (${m1.id}, 2 files)`);
  fs.writeFileSync(path.join(vault, 'Registry.json'), JSON.stringify({ buildings: [{ id: 1 }, { id: 2 }] }));
  const m2 = backup.run({ vaultDir: vault, backupDir: bdir, now: new Date('2026-10-06T10:00:00Z') });
  ok(m2.kind === 'incremental' && m2.base === m1.id && m2.changedCount === 1 && m2.files['images/a.png'].stored === m1.id && m2.files['Registry.json'].stored === m2.id && m2.verified, 'second run is incremental: only Registry.json copied, the image points back at the full');
  const v = backup.verify(bdir); ok(v.ok && v.checked === 2 && v.id === m2.id, 'verify re-hashes every file of the latest chain');
  const rt = backup.restoreTest(bdir, null, tmp); ok(rt.ok && rt.files === 2 && rt.registryParses === true && !fs.existsSync(rt.dir || '/nonexistent'), 'restore test materialises the chain, parses Registry.json and cleans up');
  fs.writeFileSync(path.join(bdir, m1.id, 'files', 'images', 'a.png'), Buffer.from('tampered')); const v2 = backup.verify(bdir); ok(!v2.ok && v2.bad.length === 1 && /a\.png/.test(v2.bad[0]), 'a tampered stored file is caught by verify');
  const m3 = backup.run({ vaultDir: vault, backupDir: bdir, now: new Date('2026-11-01T10:00:00Z') }); ok(m3.kind === 'full', 'a new month triggers a full backup');
  const lst = backup.list(bdir); ok(lst.length === 3 && lst[0].id === m3.id, 'list returns newest first');
  for (let i = 0; i < 5; i++) backup.run({ vaultDir: vault, backupDir: bdir, retain: 4, now: new Date(`2026-11-0${2 + i}T10:00:00Z`) });
  const kept = backup.manifests(bdir).map(m => m.id); ok(kept.length === 5 && kept.includes(m3.id) && !kept.includes(m1.id) && !kept.includes(m2.id), `pruning keeps the newest 4 plus the full they depend on; older runs removed (${kept.length} kept)`);
  const h = backup.health({ backupDir: bdir, vaultDir: vault, worldDir: path.join(tmp, 'world-1.18'), now: new Date('2026-11-07T00:00:00Z') }); ok(h.last && h.lastVerified && h.alerts.some(a => /restore test/.test(a.text)) && !h.alerts.some(a => a.level === 'bad'), 'health reports the last verified backup and a restore-test reminder');
  const hb = backup.health({ backupDir: path.join(tmp, 'nobackups'), vaultDir: path.join(tmp, 'missing'), worldDir: '' }); ok(hb.alerts.some(a => a.level === 'bad') && hb.alerts.some(a => /No verified backup/.test(a.text)), 'health flags a missing vault and no backups');
  console.log('\nE · bridge server');
  const cfg = { port: 0, host: '127.0.0.1', vaultDir: vault, worldDir: path.join(tmp, 'world-1.18'), backupDir: path.join(tmp, 'backups2'), mirrorDir: '', retain: 30, monthlyFull: true, afterSession: true, allowHosts: ['example.invalid'], roadBlocks: null, lastRestoreTest: null };
  const server = createServer(cfg); await new Promise(r => server.listen(0, '127.0.0.1', r)); const port = server.address().port;
  const call = (method, p, body) => new Promise((resolve, reject) => { const req = http.request({ host: '127.0.0.1', port, path: p, method, headers: { 'Content-Type': 'application/json' } }, res => { let t = ''; res.on('data', c => t += c); res.on('end', () => { try { resolve({ status: res.statusCode, headers: res.headers, body: res.headers['content-type']?.includes('json') ? JSON.parse(t) : t }); } catch (e) { reject(e); } }); }); req.on('error', reject); if (body) req.write(JSON.stringify(body)); req.end(); });
  const st = await call('GET', '/api/status'); ok(st.status === 200 && st.body.ok && st.body.vaultOk && st.body.worldOk && st.headers['access-control-allow-origin'] === '*', 'GET /api/status reports vault and world, with CORS for the file:// app');
  const pre = await new Promise((resolve, reject) => { const req = http.request({ host: '127.0.0.1', port, path: '/api/scan', method: 'OPTIONS' }, res => resolve(res.statusCode)); req.on('error', reject); req.end(); }); ok(pre === 204, 'OPTIONS preflight answered');
  const forb = await call('POST', '/api/fetch', { url: 'https://evil.example.com/x' }); ok(forb.status === 403 && /allowHosts/.test(forb.body.error), 'fetch proxy refuses hosts outside the allowlist');
  const bad = await call('GET', '/api/vault/read?name=../../etc/passwd'); ok(bad.status === 400, 'vault read refuses path traversal');
  const rd = await call('GET', '/api/vault/read?name=Registry.json'); ok(rd.status === 200 && /buildings/.test(rd.body.text), 'vault read returns Registry.json');
  const wr = await call('POST', '/api/vault/write', { name: 'notes/test.txt', text: 'hello' }); ok(wr.status === 200 && fs.readFileSync(path.join(vault, 'notes', 'test.txt'), 'utf8') === 'hello', 'vault write lands in a subfolder, atomically');
  const sc = await call('POST', '/api/scan', { bounds: { x1: 0, z1: 0, x2: 175, z2: 175 }, registry }); ok(sc.status === 200 && sc.body.ok && sc.body.clusters.length === 2 && sc.body.render && /^\/renders\/render-/.test(sc.body.render.url), `POST /api/scan returns clusters, roads, proposals and a render url (${sc.body.summary.ms} ms)`);
  const img = await call('GET', sc.body.render.url); ok(img.status === 200 && img.headers['content-type'] === 'image/png', 'the render is served as image/png');
  const last = await call('GET', '/api/scan/last'); ok(last.status === 200 && last.body.summary.clusters === 2, 'GET /api/scan/last replays the last scan');
  const bk = await call('POST', '/api/backup/run', {}); ok(bk.status === 200 && bk.body.backup.kind === 'full' && bk.body.backup.verified, 'POST /api/backup/run makes a verified backup');
  const bv = await call('POST', '/api/backup/verify', {}); ok(bv.body.result.ok, 'verify route ok');
  const rtest = await call('POST', '/api/backup/restore-test', {}); ok(rtest.body.result.ok && rtest.body.result.registryParses, 'restore-test route ok');
  const hl = await call('GET', '/api/health'); ok(hl.status === 200 && hl.body.last && hl.body.world.readable && hl.body.world.regions === 1 && Array.isArray(hl.body.alerts), 'GET /api/health reports backups, world and alerts');
  const cf = await call('POST', '/api/config', { retain: 12 }); ok(cf.body.config.retain === 12 && cfg.retain === 12, 'POST /api/config updates safe keys');
  const worldAfter = snapshot(path.join(tmp, 'world-1.18')); ok(Object.keys(worldAfter).length === 2, 'server scan left the world folder as it was');
  server.close();
  fs.rmSync(tmp, { recursive: true, force: true });
  console.log(`\n${checks - failures}/${checks} checks passed${failures ? ` · ${failures} FAILED` : ''}`);
  process.exit(failures ? 1 : 0);
})().catch(e => { console.error(e); process.exit(1); });
